tech: run ci test on update to PRs
gravitl/netclient pull request #105
Opened 2023-01-07 16:08 UTC by Aceix

retrigger CI tests on updates to PRs to master, develop, feature/*

2023-01-09 15:27 UTC, mattkasun requested changes

2023-01-09 15:27 UTC, mattkasun commented on .github/workflows/test.yml
> +      - release/*
Not sure we want this

2023-01-09 15:27 UTC, mattkasun commented on .github/workflows/test.yml
> +    types: [opened, reopened, synchronize]
with sync can probably get rid of push events....

2023-02-14 13:36 UTC, closed without merging

2023-02-14 13:37 UTC, Aceix commented
superseded by https://github.com/gravitl/netclient/pull/215