refactor migrate for new models
gravitl/netclient pull request #120
Opened 2023-01-12 15:33 UTC by mattkasun

2023-01-12 15:54 UTC, 0xdcarns requested changes

2023-01-12 15:54 UTC, 0xdcarns commented on functions/migrate.go
> +		pretty.Println(node, host, server)
are we keeping debug prints?

2023-01-12 18:32 UTC, 0xdcarns requested changes

2023-01-12 18:32 UTC, 0xdcarns commented on functions/migrate.go
> +		if err != nil {
random error check

2023-01-12 20:24 UTC, 0xdcarns approved these changes

2023-01-13 09:08 UTC, Aceix approved these changes

2023-01-13 13:59 UTC, abhishek9686 approved these changes

2023-01-13 14:07 UTC, merged