included global publish for uninstall
gravitl/netclient pull request #137
Opened 2023-01-17 21:02 UTC by 0xdcarns

To test:
- Install Netclient
- Join a network with said Netclient
- **Bonus, join with 2 netclients
- Ensure a Node is present for a host
- Call `netclient uninstall`
- Ensure the Host and Nodes are removed from the DB via UI or CLI
- **Ensure Peers are correct if other Peer netclients were connected

2023-01-17 21:08 UTC, afeiszli approved these changes

2023-01-18 21:18 UTC, theguy951357 commented
waiting on mq changes

2023-01-18 21:43 UTC, mattkasun approved these changes

2023-01-19 15:08 UTC, abhishek9686 requested changes

2023-01-19 15:08 UTC, abhishek9686 commented on functions/uninstall.go
> +	if err = PublishGlobalHostUpdate(models.DeleteHost); err != nil {
call setupMqsingleton before publishing update, since the cmd being from run the cli

2023-01-19 16:24 UTC, abhishek9686 approved these changes

2023-01-19 19:10 UTC, merged