Gra 999/proxy cmd
gravitl/netclient pull request #141
Opened 2023-01-18 17:21 UTC by abhishek9686

Review After PR #140 is merged

Testing:
1. use cmd `netclient proxy on` to turn on the proxy
    

- [ ]    verify the status proxy on UI
- [ ]    on the host check whether peer endpoint set to loop address (i.e in range of 127.0.0.1/24)
- [ ]    check wireguard connections are working

2. use cmd `netclient proxy off` to turn off proxy
     
- [ ]   verify the status proxy on UI
- [ ]   all peers endpoint should be reset to their actual public endpoints
- [ ]   check wireguard connections are working

2023-01-18 17:45 UTC, 0xdcarns requested changes

2023-01-18 17:45 UTC, 0xdcarns commented on cmd/proxy.go
> +	return status == "on"
I think there should be explicit checks for on/off, otherwise one could say `netclient proxy dfawsiuhfgi` and it would turn off.

2023-01-18 17:45 UTC, 0xdcarns commented on functions/proxy.go
> +func ChangeProxyStatus(status bool) error {
missing func comment

2023-01-18 18:35 UTC, 0xdcarns approved these changes

2023-01-18 19:21 UTC, mattkasun requested changes

2023-01-18 19:21 UTC, mattkasun commented on cmd/proxy.go
> +		if len(args) == 0 {
this check is not required if you set Args; cobra.ExactArgs(1)  at line 14.... Let corbra do the work for you.

2023-01-18 22:20 UTC, theguy951357 approved these changes
all checkmarks pass

2023-01-19 12:31 UTC, theguy951357 approved these changes

2023-01-19 17:27 UTC, merged