Gra 988/add host to network
gravitl/netclient pull request #143
Opened 2023-01-19 17:10 UTC by abhishek9686

-> add a host to network, host update logic

Testing steps: 

- [ ] On adding the host to the network check if the interface is configured - check whether network routes are added to the interface
     `ifconfig utun69 or ifconfig netmaker` to verify the routes and vice-versa for removing the host from the network

- [ ]  Check if peers of the network are added/removed 
- [ ] verify peer's connections are working

** Removing the host from the network is done via delete node logic as is

2023-01-19 19:13 UTC, 0xdcarns approved these changes

2023-01-19 20:38 UTC, mattkasun requested changes

2023-01-19 20:38 UTC, mattkasun commented on cmd/proxy.go
> +		if len(args) == 0 {
use Args: ExactArgs(1) in definition of proxyCmd

2023-01-19 20:38 UTC, mattkasun commented on cmd/proxy.go
> +		status, err := getStatus(args[0])
use ValidArgs: {"true", "false"}

2023-01-19 20:38 UTC, mattkasun commented on cmd/proxy.go
> +func getStatus(arg string) (status bool, err error) {
not required if ValidArgs: {"true", "false"} specified in cmd definition

2023-01-20 04:20 UTC, 0xdcarns approved these changes

2023-01-20 04:21 UTC, merged