Add nftables ingress and egress
gravitl/netclient pull request #206
Opened 2023-02-13 13:48 UTC by alphadose

Note:- extclients cannot ping each other via the ingress gateway

2023-02-13 15:35 UTC, mattkasun approved these changes

2023-02-13 15:44 UTC, Aceix approved these changes

2023-02-13 15:55 UTC, 0xdcarns requested changes

2023-02-13 15:55 UTC, 0xdcarns commented on nmproxy/router/nftables_linux.go
> +// CreateChains - creates default chains and rules
comment form should be nftablesManager.CreateChains -

2023-02-13 15:55 UTC, 0xdcarns commented on nmproxy/router/nftables_linux.go
> +// CleanRoutingRules cleans existing nftable resources that we created by the agent
see above

2023-02-13 15:55 UTC, 0xdcarns commented on nmproxy/router/nftables_linux.go
> +func (n *nftablesManager) DeleteRuleTable(server, ruleTableName string) {
see above

2023-02-13 15:55 UTC, 0xdcarns commented on nmproxy/router/nftables_linux.go
> +func (n *nftablesManager) InsertEgressRoutingRules(server string, egressInfo models.EgressInfo) error {
see above

2023-02-13 15:55 UTC, 0xdcarns commented on nmproxy/router/nftables_linux.go
> +// AddEgressRoutingRule - inserts an nftable rule for gateway peer
see above

2023-02-13 15:55 UTC, 0xdcarns commented on nmproxy/router/nftables_linux.go
> +func (n *nftablesManager) AddIngressRoutingRule(server, extPeerKey, extPeerAddr string, peerInfo models.PeerRouteInfo) error {
see above

2023-02-13 15:55 UTC, 0xdcarns commented on nmproxy/router/nftables_linux.go
> +// InsertIngressRoutingRules inserts an nftables rules for an ext. client to the netmaker chain and if enabled, to the nat chain
see above

2023-02-13 15:55 UTC, 0xdcarns commented on nmproxy/router/nftables_linux.go
> +// FlushAll - removes all the rules added by netmaker and deletes the netmaker chains
address all public func comments as seen above

2023-02-13 17:04 UTC, theguy951357 commented
will wait on changes

2023-02-13 17:56 UTC, 0xdcarns approved these changes

2023-02-14 12:30 UTC, abhishek9686 approved these changes

2023-02-14 18:31 UTC, theguy951357 commented
I cannot ping ext client from other server.
<img width="1440" alt="Screenshot 2023-02-14 at 1 19 05 PM" src="https://user-images.githubusercontent.com/18285922/218826052-9ef946cc-2cf3-4a86-9195-6ce94d0edffc.png">

2023-02-27 05:15 UTC, theguy951357 approved these changes
can ping ext client in an ingress gateway
can ping network from ext client.
can ping ext client from another ext client
can ping egress gateway
pr checklist passes all points
pass

2023-02-28 14:36 UTC, merged