Gra 1198 enrollment keys
gravitl/netclient pull request #223
Opened 2023-02-17 16:59 UTC by 0xdcarns

Do **not** merge until post 0.18.1
Use server branch https://github.com/gravitl/netmaker/tree/GRA-1198-enrollment_keys
Testing steps:

- [ ] Create an enrollment key for each: uses, expiration, and unlimited
- [ ] Add networks to one of them
- [ ] Ensure that the one with networks registered, also adds healthy nodes to the host that registered (daemon must be running)
- [ ] Ensure that the uses one works
- [ ] Ensure the expiration one works
- [ ] Ensure that the unlimited one works
- [ ] Ensure that: when the expiration one expires, you can not register 
- [ ] Ensure that when the uses are gone on the uses one, you can not register
- [ ] Ensure when the unlimited one is deleted, you can not register

2023-02-21 16:03 UTC, afeiszli approved these changes

2023-02-24 13:18 UTC, mattkasun requested changes

2023-02-24 13:18 UTC, mattkasun commented on cmd/register.go
> +		flags.Set("readPassFromStdIn", true)
what is point of setting this flag?

2023-02-24 13:18 UTC, mattkasun commented on cmd/register.go
> +		flags := viper.New()
lines 21- 29 should be
token, err := cmd.Flags().GetString("token")
if err != nil {
    cmd.Usage()
    return
}

2023-02-24 17:09 UTC, 0xdcarns commented on cmd/register.go
> +		flags.Set("readPassFromStdIn", true)
no idea, I copied it from join

2023-02-26 03:53 UTC, theguy951357 commented
I am having trouble getting nodes successfully connected on this one.
I have netmaker and netclient built on the branches.
I use the create enrollment key api call mentioned on GRA-1198-enrollment_keys 
I then use the token created to call netclient register -t <token> on two nodes.
nodes show up on the UI.
netclient list returns "no such network"
nodes cannot ping eachother.

2023-02-28 14:24 UTC, theguy951357 approved these changes
checkmarks pass on the pr

critical pr list 100%

pass

2023-02-28 14:34 UTC, merged