Feature support gui
gravitl/netclient pull request #26
Opened 2022-11-29 14:36 UTC by mattkasun

functions updated to support use from gui version

2022-11-29 16:18 UTC, 0xdcarns commented on functions/join.go
> +	pretty.Println(nodeGET)
do we need this pretty print here?

2022-11-29 16:30 UTC, Aceix reviewed
Can you add the JSON tags for Node, Server maybe and Config structs? so wails will generate the respective typescript .d.ts files

2022-11-29 18:35 UTC, 0xdcarns approved these changes

2022-11-29 18:39 UTC, 0xdcarns requested changes

2022-11-29 18:39 UTC, 0xdcarns commented on cmd/leave.go
> +			fmt.Println("successful left network ", args[0])
successfully?

2022-11-29 19:03 UTC, Aceix approved these changes

2022-11-30 12:51 UTC, 0xdcarns approved these changes

2022-11-30 12:52 UTC, merged