Feature stop interface
gravitl/netclient pull request #27
Opened 2022-11-29 20:36 UTC by mattkasun

2022-11-29 20:41 UTC, 0xdcarns requested changes

2022-11-29 20:41 UTC, 0xdcarns commented on functions/daemon.go
> +			logger.Log(0, "closing netamaker interface")
netamaker -> netmaker

2022-11-29 20:41 UTC, 0xdcarns commented on cmd/leave.go
> +			fmt.Println("successful left network ", args[0])
successfully..

2022-11-29 21:07 UTC, mattkasun commented on functions/daemon.go
> +			logger.Log(0, "closing netamaker interface")
fixed typo

2022-11-30 15:00 UTC, 0xdcarns approved these changes

2022-12-02 14:17 UTC, merged