GRA-1339: host pull
gravitl/netclient pull request #290
Opened 2023-03-22 19:39 UTC by 0xdcarns

## Describe your changes
- removed arguments from pull
- pull gets from every server
## Provide Issue ticket number if applicable/not in title
title.
## Provide link to Netmaker PR if required
https://github.com/gravitl/netmaker/pull/2142
## Provide testing steps

- [ ] see NM PR

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-03-22 20:08 UTC, mattkasun requested changes

2023-03-22 20:08 UTC, mattkasun commented on gui/exported.go
> +func (app *App) GoPullLatestNodeConfig(network string) error {
Exported wails func can return (data) or (data, err)
sig should be func (app *App) GoPullLatestNodeConfig(network string) (any, err)

2023-03-22 20:08 UTC, mattkasun commented on gui/exported.go
> +	return nil
return nil, nil

2023-03-23 19:51 UTC, mattkasun approved these changes

2023-03-24 13:08 UTC, theguy951357 approved these changes
pr steps pass
critical list 100%
this fixes the pull issue on GRA-1435

2023-03-24 14:20 UTC, abhishek9686 approved these changes

2023-03-24 14:25 UTC, merged