hotfix release workflow
gravitl/netclient pull request #324
Opened 2023-04-03 14:12 UTC by theguy951357

## Describe your changes

## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required

## Provide testing steps

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-04-03 23:12 UTC, 0xdcarns approved these changes

2023-04-04 13:03 UTC, mattkasun approved these changes

2023-04-04 13:53 UTC, Aceix requested changes

2023-04-04 13:53 UTC, Aceix commented on .github/workflows/hotfix-release.yml
> +    needs: release-branch
same

2023-04-04 13:53 UTC, Aceix commented on .github/workflows/hotfix-release.yml
> +    needs: release-branch
same

2023-04-04 13:53 UTC, Aceix commented on .github/workflows/hotfix-release.yml
> +    needs: release-branch
same

2023-04-04 13:53 UTC, Aceix commented on .github/workflows/hotfix-release.yml
> +          git switch -c release_${{ github.event.inputs.version }}
`-c` flag not required since the release branch will already be present in a hotfix scenario

2023-04-04 13:56 UTC, Aceix commented on .github/workflows/hotfix-release.yml
> +    needs: release-branch
change to `update-tag`?

2023-04-04 16:19 UTC, Aceix approved these changes

2023-04-04 19:21 UTC, merged