GRA-1205: internet gateways
gravitl/netclient pull request #337
Opened 2023-04-07 16:29 UTC by 0xdcarns

## Describe your changes
Internet gateways on **linux** only work with this PR
Will merge after Mac and Windows complete initial PRs

## Provide Issue ticket number if applicable/not in title
title.
## Provide link to Netmaker PR if required
- https://github.com/gravitl/netmaker/pull/2182
## Provide testing steps
- [ ] Ensure that an egress gateway with 0.0.0.0/0 functions as an internet gateway for a connected linux peer

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-04-07 18:16 UTC, afeiszli requested changes
In order to compile on Windows, should have unimplemented functions in routes_windows (see workflow failures)

2023-04-07 20:03 UTC, 0xdcarns commented
> In order to compile on Windows, should have unimplemented functions in routes_windows (see workflow failures)

I state in PR won't be merged till other ones are in...

2023-04-12 05:46 UTC, theguy951357 commented
I still have nodes freezing up when I set an egress gateway to 0.0.0.0/0

2023-04-14 21:17 UTC, theguy951357 approved these changes
pr passes
critical list passes

2023-04-18 10:26 UTC, mattkasun requested changes

2023-04-18 10:26 UTC, mattkasun commented on config/config.go
> +		aIP := allowedIPs[i]
use 
```
func peerHasIp(ip *net.IPNet, allowedIPs []net.IPNet) bool {
    if ip.Contains(allowedIPs[i].IP) {
        return true
    }
    return false
}
```

2023-04-18 16:20 UTC, afeiszli approved these changes

2023-04-18 17:34 UTC, merged