refactor refresh of wireguard keys
gravitl/netclient pull request #348
Opened 2023-04-13 21:59 UTC by mattkasun

## Describe your changes
key updates are handled in host updates with updateaction = UpdateKeys
## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required

## Provide testing steps
see GRA-1529

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-04-14 13:22 UTC, 0xdcarns requested changes

2023-04-14 13:22 UTC, 0xdcarns commented on functions/daemon.go
> +	pretty.Println("current keys", host.PrivateKey.String(), host.PublicKey.String())
debug log

2023-04-14 13:22 UTC, 0xdcarns commented on functions/daemon.go
> +	pretty.Println("new private key", host.PrivateKey.String())
debug log

2023-04-14 13:22 UTC, 0xdcarns commented on functions/daemon.go
> +	pretty.Println("new public key", host.PublicKey.String())
debug log

2023-04-14 14:19 UTC, mattkasun commented on functions/daemon.go
> +	pretty.Println("current keys", host.PrivateKey.String(), host.PublicKey.String())
debug logs removed

2023-04-15 17:12 UTC, theguy951357 approved these changes
pr passes
critical list passes

2023-04-17 07:56 UTC, Aceix approved these changes

2023-04-18 02:54 UTC, theguy951357 approved these changes
pr steps pass
critical list passes

2023-04-18 13:22 UTC, abhishek9686 commented on functions/mqhandlers.go
> +		UpdateKeys(client)
why is it required to pass mq client as parameter to `UpdateKeys`

2023-04-19 01:38 UTC, mattkasun commented
depends on netmaker PR -- 2199
do not merge until 2199 is merged and go.mod updated

2023-04-19 18:13 UTC, abhishek9686 approved these changes

2023-04-19 19:28 UTC, merged