GRA-1385: added sso/basic auth registration back
gravitl/netclient pull request #353
Opened 2023-04-17 21:17 UTC by 0xdcarns

## Describe your changes
- Added ability to join/register via SSO or basic auth
## Provide Issue ticket number if applicable/not in title
title.
## Provide link to Netmaker PR if required
- https://github.com/gravitl/netmaker/pull/2214

## Provide testing steps

- [ ] see NM PR

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-04-17 22:35 UTC, mattkasun requested changes

2023-04-17 22:35 UTC, mattkasun commented on cmd/join.go
> +server: netclient register -s <server> // join a specific server via SSO if Oauth configured
should these all be netclient join vice netclient register

2023-04-17 22:59 UTC, theguy951357 approved these changes
pr steps pass
critical list passes
pending changes addressed

2023-04-18 12:54 UTC, mattkasun approved these changes

2023-04-18 13:33 UTC, merged