create explicit routes when internet gateway exist
gravitl/netclient pull request #361
Opened 2023-04-21 13:34 UTC by mattkasun

## Describe your changes
skip creation of explicit server & peer routes if internet gateway not present
## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required
n/a
## Provide testing steps
see GRA-1554
## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-04-25 12:00 UTC, abhishek9686 requested changes

2023-04-25 12:00 UTC, abhishek9686 commented on routes/routes_linux.go
need these changes on other OS too

2023-04-25 18:30 UTC, abhishek9686 commented on routes/routes_unix.go
what about check under func `SetNetmakerPeerEndpointRoutes` ?

2023-04-25 18:31 UTC, abhishek9686 commented on routes/routes_windows.go
check under func `SetNetmakerPeerEndpointRoutes` is missing

2023-04-25 19:43 UTC, abhishek9686 approved these changes

2023-04-28 18:12 UTC, afeiszli approved these changes

2023-04-28 18:12 UTC, afeiszli commented
Approved, but question for future sprint. Do we need a separate ticket to handle removing routes if gateway is removed?

2023-04-28 19:46 UTC, mattkasun commented
> Approved, but question for future sprint. Do we need a separate ticket to handle removing routes if gateway is removed?

NET-36 created

2023-05-02 20:47 UTC, merged