GRA-1494: Turn client side implementation
gravitl/netclient pull request #371
Opened 2023-04-26 13:31 UTC by abhishek9686

## Describe your changes

## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required

## Provide testing steps

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [x] I have performed a self-review of my code and tested it.
- [x] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [x] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [x] Netclient & Netmaker are awesome.

2023-04-26 20:03 UTC, mattkasun requested changes

2023-04-28 00:54 UTC, abhishek9686 commented on auth/auth.go
> +package auth
due to cyclic dependency

2023-04-28 01:00 UTC, abhishek9686 commented on nmproxy/config/peer_config.go
> +	t, ok = c.ifaceConfig.hostTurnCfg[server]
when you return map[key] it just returns value, second parameter (bool) is skipped

2023-04-28 01:05 UTC, abhishek9686 commented on nmproxy/turn/turn_helper.go
> +						logger.Log(0, fmt.Sprintf("-------> Turn Peer Addr Has Been Changed From %s to %s", t.PeerTurnAddr, signal.TurnRelayEndpoint))
will remove it, added for debugging

2023-04-28 01:08 UTC, abhishek9686 commented on nmproxy/turn/turn.go
> +package turn
turn connections are handled by proxy, it makes sense to keep it within the proxy

2023-04-28 18:11 UTC, afeiszli approved these changes

2023-04-28 19:54 UTC, mattkasun approved these changes

2023-05-02 19:50 UTC, theguy951357 approved these changes
pr passes
critical list passes

2023-05-02 20:48 UTC, merged