check for available http port
gravitl/netclient pull request #374
Opened 2023-04-27 20:16 UTC by mattkasun

## Describe your changes
netclient daemon gets available port for http server
port is saved to config file
netclient-gui uses config file to set http endpoint

## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required

## Provide testing steps
see NET-29
## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-04-28 05:45 UTC, afeiszli commented
Just a general comment, but this is a lot of changes for a relatively small problem. Can you explain why so many files need to be touched for this?

2023-04-28 06:13 UTC, Aceix commented
FreeBSD build is broken, static check fails

2023-04-28 07:24 UTC, abhishek9686 requested changes

2023-04-28 11:37 UTC, mattkasun commented
> 

most of the changes are to ensure that when /etc/netclient is created, it is created with the correct permissions

2023-04-28 14:47 UTC, mattkasun commented on functions/httpserver.go
> +	port, err := ncutils.GetFreeTCPPort(8000)
simplified GetFreeTCPPort

2023-04-28 18:09 UTC, afeiszli commented
> > 
> 
> most of the changes are to ensure that when /etc/netclient is created, it is created with the correct permissions

shouldn't that be a separate PR, or does that relate to the port issue?

2023-04-28 21:27 UTC, mattkasun commented
It relates to port issue .  Permissions need to be correct or the unprivileged Gui would not be able to read it's config file

2023-04-29 00:26 UTC, Aceix approved these changes

2023-05-01 13:38 UTC, afeiszli approved these changes

2023-05-01 15:33 UTC, theguy951357 approved these changes
pr steps pass
critical list passes

2023-05-01 15:39 UTC, merged