status endpoint so gui can check if running
gravitl/netclient pull request #375
Opened 2023-04-28 18:18 UTC by mattkasun

## Describe your changes
/status endpoint added to http server
on gui startup, app exits if it does not get response (temp solution)

## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required

## Provide testing steps
see Net-6
## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-04-28 18:54 UTC, abhishek9686 requested changes

2023-04-28 18:54 UTC, abhishek9686 commented on gui/main.go
fix static check

2023-04-28 20:08 UTC, Aceix approved these changes

2023-05-01 13:03 UTC, afeiszli approved these changes

2023-05-01 17:46 UTC, theguy951357 approved these changes
pr passes
critical list passes

2023-05-01 17:54 UTC, merged