peer updates for refactored relays
gravitl/netclient pull request #416
Opened 2023-05-24 09:14 UTC by mattkasun

## Describe your changes
peer updates for refactored relays

## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required
https://github.com/gravitl/netmaker/pull/2333/

## Provide testing steps
see NET-127

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-05-24 13:33 UTC, Aceix commented on config/config.go
> -	HostPeers         map[string][]wgtypes.PeerConfig `json:"peers" yaml:"peers"`
this might need a ticket to update ncgui 🤔

2023-05-25 14:32 UTC, abhishek9686 requested changes

2023-05-25 14:32 UTC, abhishek9686 commented on functions/mqhandlers.go
> +	host.FirewallInUse = hostCfg.FirewallInUse
I believe these changes are from a different branch?
how are these changes related to this relay PR?

2023-05-25 21:52 UTC, afeiszli reviewed
@mattkasun maybe I'm missing something but the "Files changed" tab is only showing a change to two logger logs, and the go mod/sum. Delta does not appear relevant to peer updates or relay.

2023-05-27 14:38 UTC, merged