Net 186
gravitl/netclient pull request #420
Opened 2023-05-26 14:36 UTC by abhishek9686

## Describe your changes

## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required

## Provide testing steps

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-05-29 12:17 UTC, mattkasun approved these changes

2023-05-30 12:30 UTC, TobiaszCudnik requested changes

2023-05-30 23:22 UTC, theguy951357 approved these changes
pr passes
critical list passes

2023-05-31 09:20 UTC, TobiaszCudnik approved these changes

2023-05-31 09:34 UTC, merged