NET-288 kill daemon on uninstall
gravitl/netclient pull request #445
Opened 2023-06-07 12:01 UTC by TobiaszCudnik

## Describe your changes

NET-288 kill daemon on uninstall

## Provide testing steps

https://toil.kitemaker.co/cQARgD-Gravitl/6a50SD-Netmaker/items/288

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-06-07 12:28 UTC, mattkasun requested changes
what about changes to common_darwin, common_freebsd, common_windows?

2023-06-07 12:56 UTC, TobiaszCudnik commented on daemon/common_unix.go
> +	slog.Info("Sending signal", s, "to PID", p)
Docs: https://pkg.go.dev/golang.org/x/exp/slog
First example: `slog.Info("hello", "count", 3)`

2023-06-08 10:35 UTC, afeiszli approved these changes

2023-06-08 10:46 UTC, Aceix approved these changes

2023-06-08 11:11 UTC, mattkasun requested changes
slog call has incorrect number of args

2023-06-08 12:17 UTC, TobiaszCudnik commented on daemon/common_unix.go
> +	slog.Info("Sending signal", s, "to PID", p)
Fixed.

2023-06-08 12:19 UTC, mattkasun approved these changes

2023-06-08 12:20 UTC, mattkasun approved these changes

2023-06-08 12:38 UTC, abhishek9686 approved these changes

2023-06-08 19:36 UTC, theguy951357 approved these changes
critical list passes

ps -aef | grep -i netclient shows no daemon running after uninstall command

2023-06-08 21:21 UTC, merged