Netclient darwin fixes
gravitl/netclient pull request #45
Opened 2022-12-05 19:44 UTC by abhishek9686

2022-12-05 19:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gravitl/netclient?pullRequest=45) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gravitl/netclient?pullRequest=45) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gravitl/netclient?pullRequest=45) it.</sub>

2022-12-05 21:06 UTC, 0xdcarns commented on wireguard/wireguard_conf.go
> +	file := config.GetNetclientPath() + ncutils.GetInterfaceName() + ".conf"
I thought we had decided to only use netmaker for the conf file name?

2022-12-05 21:07 UTC, 0xdcarns approved these changes

2022-12-05 22:30 UTC, mattkasun requested changes

2022-12-06 04:03 UTC, abhishek9686 commented on ncutils/netclientutils.go
> +func GetInterfaceName() string {
it was moved to avoid cyclic dependency in packages

2022-12-06 04:08 UTC, abhishek9686 commented on functions/daemon.go
> +	file := config.GetNetclientPath() + ncutils.GetInterfaceName() + ".conf"
changed it to always use `netmaker.conf`

2022-12-06 15:15 UTC, 0xdcarns approved these changes

2022-12-06 17:52 UTC, mattkasun approved these changes

2022-12-06 18:16 UTC, merged