update develop to v0.20.3
gravitl/netclient pull request #470
Opened 2023-06-20 20:00 UTC by theguy951357

## Describe your changes
updating develop to v0.20.3
## Provide Issue ticket number if applicable/not in title
no ticket number
## Provide link to Netmaker PR if required

## Provide testing steps
no testing needed
## Checklist before requesting a review
- [x] My changes affect only 10 files or less.
- [x] I have performed a self-review of my code and tested it.
- [x] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [x] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [x] Netclient & Netmaker are awesome.

2023-06-20 21:00 UTC, mattkasun approved these changes

2023-06-21 13:59 UTC, Aceix requested changes
can the gui version be updated as well. check `gui/main.go` file

2023-06-21 16:52 UTC, abhishek9686 commented
> can the gui version be updated as well. check `gui/main.go` file

will this be in a separate PR?

2023-06-21 17:58 UTC, theguy951357 commented
> 

updated

2023-06-22 10:13 UTC, abhishek9686 requested changes

2023-06-22 10:13 UTC, abhishek9686 commented on gui/main.go
> +var version = "v0.22.3"
supposed to be `v0.20.3`?

2023-06-23 04:40 UTC, abhishek9686 approved these changes

2023-06-23 10:05 UTC, Aceix approved these changes

2023-06-23 11:00 UTC, merged