windows binary path
gravitl/netclient pull request #472
Opened 2023-06-21 12:20 UTC by mattkasun

## Describe your changes
install windows binary in correct directory

2023-06-21 13:17 UTC, Aceix requested changes

2023-06-21 19:50 UTC, mattkasun commented on ncutils/netclientutils_windows.go
> -const WIN_PATH = "C:\\Program Files (x86)\\Netclient\\"
can't. cyclic dependency

2023-06-22 12:07 UTC, Aceix approved these changes

2023-06-22 12:38 UTC, mattkasun commented on ncutils/windowsdaemon/winsw.exe
Because it is embedded

2023-06-22 14:07 UTC, afeiszli commented
Need to take into consideration how this affects upgrades. Would assume this leads to a duplicate netclient.

2023-06-23 10:33 UTC, TobiaszCudnik approved these changes

2023-06-28 17:17 UTC, merged