fix(NET-347): deduce public endpoint on daemon start
gravitl/netclient pull request #474
Opened 2023-06-23 12:34 UTC by Aceix

## Describe your changes

## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required

## Provide testing steps

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-06-23 13:03 UTC, afeiszli approved these changes

2023-06-23 17:42 UTC, mattkasun requested changes

2023-06-26 05:06 UTC, abhishek9686 requested changes

2023-06-26 05:07 UTC, abhishek9686 commented on functions/daemon.go
> +	stunServers := []models.StunServer{
yes, will be removed from server

2023-06-26 15:36 UTC, abhishek9686 approved these changes

2023-06-26 15:43 UTC, mattkasun approved these changes

2023-06-27 15:51 UTC, merged