Fix errors in error messages
gravitl/netclient pull request #476
Opened 2023-06-26 07:11 UTC by TobiaszCudnik

## Describe your changes

Fix errors in error messages

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-06-26 11:49 UTC, Aceix approved these changes

2023-06-26 13:45 UTC, mattkasun requested changes

2023-06-26 13:45 UTC, mattkasun commented on functions/daemon.go
> +		slog.Error("unable to subscribe to all dns updates", "host", hostID, "server", server, "error", token.Error())
change also applicable to line 339, 405, 420, 425

2023-06-28 17:46 UTC, mattkasun approved these changes

2023-06-28 17:56 UTC, afeiszli approved these changes

2023-06-28 17:56 UTC, merged