replace peers on peer/host update
gravitl/netclient pull request #491
Opened 2023-07-07 17:04 UTC by mattkasun

2023-07-07 21:08 UTC, theguy951357 approved these changes
pr steps pass
critical list passes

2023-07-10 02:13 UTC, abhishek9686 requested changes

2023-07-10 02:13 UTC, abhishek9686 commented on functions/mqhandlers.go
doing this on every peer update, the connection will get reset and it halts any ongoing transfers
why was this change necessary?

2023-07-10 09:37 UTC, mattkasun commented on functions/mqhandlers.go
NET-419

2023-07-10 14:18 UTC, abhishek9686 requested changes

2023-07-10 14:18 UTC, abhishek9686 commented on functions/mqhandlers.go
This PR will solve the issue with peer deletions: https://github.com/gravitl/netmaker/pull/2445
we shouldn't be replacing peers on every peer update, it will interfere with active connections, it's a costly operation it becomes more evident on scale
for your reference: https://github.com/WireGuard/wireguard-go/blob/469159ecf7d108dc1d44f8789dedbb463b7bd3a6/device/uapi.go#L243

2023-07-10 14:23 UTC, mattkasun commented on functions/mqhandlers.go
this is an interim fix until peer update refactor is complete

2023-07-10 14:30 UTC, abhishek9686 commented on functions/mqhandlers.go
this PR has the fixes needed:  https://github.com/gravitl/netmaker/pull/2445

2023-07-10 14:36 UTC, abhishek9686 commented on functions/mqhandlers.go
and peer update refactor won't go in until a couple of releases

2023-07-12 20:26 UTC, mattkasun commented
obe due to https://github.com/gravitl/netmaker/pull/2445

2023-07-12 20:26 UTC, closed without merging