don't close wg interface on soft reset
gravitl/netclient pull request #548
Opened 2023-08-17 17:37 UTC by mattkasun

2023-08-22 06:31 UTC, abhishek9686 approved these changes

2023-08-23 11:20 UTC, Aceix approved these changes

2023-08-29 13:05 UTC, theguy951357 approved these changes
tested and passed

2023-08-30 02:26 UTC, abhishek9686 requested changes

2023-08-30 02:26 UTC, abhishek9686 commented on functions/daemon.go
On soft restart, you shouldn't stun, The bug was reported by @theguy951357, but I don't see any changes for that

2023-08-30 02:35 UTC, mattkasun commented on functions/daemon.go
Not reproducable

2023-08-30 04:53 UTC, abhishek9686 commented on functions/daemon.go
even if it's not reproducible, it's pretty evident it can happen again

2023-08-30 18:43 UTC, abhishek9686 approved these changes

2023-08-30 18:43 UTC, merged