NET-464
gravitl/netclient pull request #549
Opened 2023-08-17 19:43 UTC by uGiFarukh

* On both connect and disconnect cli commands, notifying the user about specifying the network name.

* On both connect and disconnect cli commands, listing out the network names that the netclient have access to.

* Also showing no networks available message if the netclient do not have access to any networks.

## Describe your changes
Added network list upon executing the connect and disconnect cli commands without any arguments.

## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required

## Provide testing steps
1. Connect netclient to one or more networks.
2. Use command -> "netclient connect" or "netclient disconnect" without any arguments.
3. This should provide a more helpful message and list out the networks netclient have access to.
4. Remove the host from a specific network and try step 3 again. This should provide an updated list of networks that netclient have access to after the removal from a network.
5. Remove the netclient from all networks. Repeat step 3 and now it should report that no networks are available.

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-08-17 20:17 UTC, mattkasun requested changes

2023-08-17 20:17 UTC, mattkasun commented on cmd/connect.go
> +			fmt.Println("\nPlease specify the network name as the first argument. For example: netclient connect my-network-name")
first argument implies that multiple args can be provided

2023-08-17 20:17 UTC, mattkasun commented on cmd/disconnect.go
> +			fmt.Println("\nPlease specify the network name as the first argument. For example: netclient disconnect my-network-name")
remove 'first'

2023-08-18 09:27 UTC, uGiFarukh commented on cmd/disconnect.go
> +			fmt.Println("\nPlease specify the network name as the first argument. For example: netclient disconnect my-network-name")
changed the message.

2023-08-18 11:55 UTC, mattkasun approved these changes

2023-08-22 06:27 UTC, abhishek9686 approved these changes

2023-08-22 06:34 UTC, merged