local endpoint detection.
gravitl/netclient pull request #569
Opened 2023-09-06 15:30 UTC by mattkasun

2023-09-07 06:51 UTC, abhishek9686 requested changes

2023-09-07 06:51 UTC, abhishek9686 commented on wireguard/wireguard.go
> -	peers = peer.SetPeersEndpointToProxy(peers)
why was this removed?
we still use proxy for turn

2023-09-08 04:23 UTC, abhishek9686 requested changes

2023-09-08 04:23 UTC, abhishek9686 commented on wireguard/wireguard.go
> +	GetInterface().Config.Peers = peers
this should be moved above `SetPeersEndpointToProxy`

2023-09-13 04:47 UTC, abhishek9686 approved these changes

2023-09-18 08:03 UTC, Aceix approved these changes

2023-09-18 08:04 UTC, merged