[NET-562] Adapt to net-562 on netmaker side
gravitl/netclient pull request #596
Opened 2023-09-25 18:27 UTC by gabrielseibel1

## Describe your changes
Move PKA from node to host level

## Provide testing steps
Described in ticket

2023-09-26 11:47 UTC, mattkasun requested changes

2023-09-26 11:47 UTC, mattkasun commented on config/node.go
> +	"net"
imports require re-ordering

2023-09-26 11:47 UTC, mattkasun commented on config/oldconfig.go
> +	"github.com/devilcove/httpclient"
re-order imports

2023-09-28 10:51 UTC, abhishek9686 commented
client-side changes are not expected and are not required for NET-562

2023-09-28 14:36 UTC, gabrielseibel1 commented on config/node.go
> +	"net"
https://github.com/gravitl/netclient/pull/596/commits/e4a236844452966cac1874bc33edf158805e4ccf

2023-09-28 14:41 UTC, abhishek9686 commented
> > client-side changes are not expected and are not required for NET-562
> 
> @abhishek9686 How will the interfaces be correctly setup without updating them with the PKAs of the hosts?

PKA is set on the peer config not on the host's interface

2023-10-01 19:49 UTC, closed without merging