[NET-623] Disable gui server by default for netclient docker
gravitl/netclient pull request #613
Opened 2023-10-18 18:18 UTC by gabrielseibel1

## Describe your changes
Disable gui server by default for netclient docker, allowing override with a build arg

## Provide testing steps
docker-build it with no args, run the resulting image: prints "[netclient] disabling gui server"
docker-build it with `--build-arg gui_server_disable=""`, run it: doesn't print the message
the message is bound to be echoed before we run `/root/netclient guiServer disable`, but if you want to be thorough you can also query the gui server apis to see if it's on or not.

2023-10-19 13:24 UTC, mattkasun approved these changes

2023-10-20 06:44 UTC, abhishek9686 requested changes

2023-10-20 06:44 UTC, abhishek9686 commented on Dockerfile
> +ARG gui_server_disable="true"
there is no need add this as arg, you can never use GUI for docker

2023-10-20 06:47 UTC, abhishek9686 requested changes

2023-10-20 06:47 UTC, abhishek9686 commented on Dockerfile
> +# i.e.: `docker build ... --build-arg gui_server_disable=""` to enable it
`gui_server_disable` should accept true or false

2023-10-20 06:54 UTC, abhishek9686 commented
@gabrielseibel1 resolve merge conflicts

2023-10-25 08:59 UTC, Aceix commented
merge confilcts

2023-10-26 10:51 UTC, abhishek9686 requested changes

2023-10-26 10:51 UTC, abhishek9686 commented on Dockerfile
remove the build arg, are you expecting user to build the image in order enable GUI?
it should just accept env `GUI_SERVER_ENABLED`

2023-10-26 10:51 UTC, abhishek9686 commented on scripts/netclient.sh
`/root/netclient guiServer disable` by default 
only check if ${GUI_SERVER_ENABLED} is set to true to enable it

2023-11-01 16:44 UTC, abhishek9686 approved these changes

2023-11-02 18:55 UTC, theguy951357 approved these changes

2023-11-06 10:44 UTC, merged