fix(NET-711): remove all lockfiles on daemon start
gravitl/netclient pull request #627
Opened 2023-11-09 12:13 UTC by Aceix

## Describe your changes

## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required

## Provide testing steps

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-11-09 14:02 UTC, mattkasun approved these changes

2023-11-20 11:27 UTC, abhishek9686 requested changes

2023-11-20 11:27 UTC, abhishek9686 commented on daemon/common.go
> +		return err
don't return on err, you an log them

2023-11-20 11:27 UTC, abhishek9686 commented on daemon/common.go
> +	if err := removeAllLockFiles(); err != nil {
can you invoke this under Daemon() func

2023-11-20 11:55 UTC, abhishek9686 approved these changes

2023-11-22 20:37 UTC, theguy951357 approved these changes

2023-11-27 11:14 UTC, merged