NET-671
gravitl/netclient pull request #630
Opened 2023-11-13 05:41 UTC by uGiFarukh

## Describe your changes
* Fixed windows netclient egress routes add

## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required

## Provide testing steps
1. Create an egress gateway using another linux machine under the same netmaker network.
2. Add a windows netclient with this PR branch to any netmaker network.
3. Test from the windows netclient if those egress ranges are reachable through the windows netclient.

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-11-13 06:04 UTC, abhishek9686 requested changes

2023-11-13 06:04 UTC, abhishek9686 commented on wireguard/wireguard_windows.go
> +			addr.Network.String(), ncutils.GetInterfaceName(), "0.0.0.0", "active")
handle ipv6 route setting as well

2023-11-13 11:13 UTC, uGiFarukh commented on wireguard/wireguard_windows.go
> +			addr.Network.String(), ncutils.GetInterfaceName(), "0.0.0.0", "active")
ipv6 support added

2023-11-22 08:58 UTC, abhishek9686 approved these changes

2023-11-22 08:58 UTC, merged