NET-814: Deprecating TURN
gravitl/netclient pull request #648
Opened 2023-12-07 18:36 UTC by abhishek9686

## Describe your changes

## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required

## Provide testing steps

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2023-12-11 12:47 UTC, Aceix requested changes

2023-12-11 12:47 UTC, Aceix commented on functions/fail_over.go
> +	}
missing defer res body close?

2023-12-13 09:59 UTC, abhishek9686 commented on functions/fail_over.go
> +	}
that is handled within the pkg

2023-12-13 18:46 UTC, theguy951357 approved these changes

2023-12-13 18:49 UTC, merged