Feature ingress routing
gravitl/netclient pull request #66
Opened 2022-12-12 19:48 UTC by abhishek9686

2022-12-14 14:57 UTC, 0xdcarns commented on main.go
> -//go:embed all:gui/frontend/dist
This is required

2022-12-14 15:04 UTC, mattkasun requested changes

2022-12-14 17:51 UTC, abhishek9686 commented on nmproxy/config/router_config.go
> +package config
models pkg has other structs too, not all belong to config pkg

2022-12-16 15:04 UTC, mattkasun approved these changes

2022-12-16 15:18 UTC, merged