darwin: support for dual stack addrs
gravitl/netclient pull request #73
Opened 2022-12-14 12:51 UTC by abhishek9686

2022-12-14 14:54 UTC, 0xdcarns approved these changes

2022-12-14 15:02 UTC, mattkasun requested changes

2022-12-14 15:04 UTC, 0xdcarns commented on wireguard/types.go
> +			IP6:      node.Address6.IP,
I think it's nice to have them grouped per node like this

2022-12-16 15:20 UTC, 0xdcarns approved these changes

2022-12-16 15:21 UTC, merged