NET-1608:increase peerConnectionCheck interval to 1 min
gravitl/netclient pull request #890
Opened 2024-10-03 10:06 UTC by yabinma

## Describe your changes

## Provide Issue ticket number if applicable/not in title

## Provide link to Netmaker PR if required

## Provide testing steps

## Checklist before requesting a review
- [ ] My changes affect only 10 files or less.
- [ ] I have performed a self-review of my code and tested it.
- [ ] If it is a new feature, I have added thorough tests, my code is <= 1450 lines.
- [ ] If it is a bugfix, my code is <= 200 lines.
- [ ] My functions are <= 80 lines.
- [ ] I have had my code reviewed by a peer.
- [ ] My unit tests pass locally.
- [ ] Netclient & Netmaker are awesome.

2024-10-03 16:00 UTC, abhishek9686 approved these changes

2024-10-07 13:20 UTC, yabinma commented
Close it and I will raise a new one.

2024-10-07 14:42 UTC, yabinma commented
reopen with new code change.

2024-10-08 03:31 UTC, abhishek9686 requested changes

2024-10-08 03:31 UTC, abhishek9686 commented on functions/daemon.go
> +	config.UpdateHostPeers(pullresp.Peers)
duplicate func call, we already update config in Pull above

2024-10-10 10:33 UTC, abhishek9686 approved these changes

2024-10-10 10:34 UTC, merged